services:
  mongodb:
    image: mongo:8.0.10
    container_name: content-storage-mongodb
    ports:
      - "27017:27017" # Map container port 27017 to host port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      # For production, should use Docker secrets or a more robust secret management solution
    volumes:
      - mongodb_data:/data/db # Persist data to a named volume
      
  rabbitmq:
    image: rabbitmq:4.1.1-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17.5
    container_name: postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist PostgreSQL data

volumes:
  mongodb_data:
  rabbitmq_data:
  postgres_data: