services:
  mongodb:
    image: mongo:8.0.10
    container_name: content-storage-mongodb
    ports:
      - "27017:27017" # Map container port 27017 to host port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      # For production, should use Docker secrets or a more robust secret management solution
    volumes:
      - mongodb_data:/data/db # Persist data to a named volume
      
  rabbitmq:
    image: rabbitmq:4.1.1-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"

volumes:
  mongodb_data: # Define the named volume
  rabbitmq_data: # Define the named volume for RabbitMQ