spring:
  # --- Security Configuration ---
  # This section configures the API Gateway to act as an OAuth2 Resource Server.
  # It will validate incoming JWTs against the provided Keycloak realm.
  security:
    oauth2:
      resourceserver:
        jwt:
          # The gateway uses this to fetch the public keys required to verify the JWT signature.
          issuer-uri: ${KEYCLOAK_ISSUER}

  # --- Gateway Routing Configuration ---
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Unique identifier for the route to the Content Storage Service (CSS).
            - id: content-storage-service-route
            
              # Requests matching the predicate will be forwarded here.
              uri: http://localhost:8083

              # Predicates define the conditions for a request to be routed.
              predicates:
                # This predicate matches if the request path starts with /api/v1/content.
                # The '/**' is a wildcard that matches any subpath.
                - Path=/api/v1/content/**
              filters:
                # This applies our filter that adds the X-User-ID header
                - AddUserIdHeader
            - id: notification-service-route
            
              uri: http://localhost:8086

              predicates:
                # This predicate matches if the request path starts with /api/v1/notifications.
                - Path=/api/v1/notifications/**
              filters:
                # This applies our filter that adds the X-User-ID header
                - AddUserIdHeader

            # Route for private Payment Service endpoints
            - id: payment-service-private
              uri: http://localhost:8087 # Internal network address
              predicates:
                - Path=/api/v1/payments/**, /api/v1/balance/**
              filters:
                # This applies our filter that adds the X-User-ID header
                - AddUserIdHeader

            # PUBLIC route for the Stripe webhook
            - id: payment-service-webhook-public
              uri: http://localhost:8087 # Still points to the same internal service
              predicates:
                # This route ONLY matches the webhook path
                - Path=/api/v1/stripe/webhooks
              # There are no authentication filters on this route
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:3000"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                allowed-headers:
                  - Authorization
                  - Content-Type
                  - Stripe-Signature
                allow-credentials: true
                #max-age: 3600