spring:
  # --- Gateway Routing Configuration ---
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ...
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true
            #maxAge: 3600