spring:
  # --- Security Configuration ---
  # This section configures the API Gateway to act as an OAuth2 Resource Server.
  # It will validate incoming JWTs against the provided Keycloak realm.
  security:
    oauth2:
      resourceserver:
        jwt:
          # The gateway uses this to fetch the public keys required to verify the JWT signature.
          issuer-uri: ${KEYCLOAK_ISSUER}

  # --- Gateway Routing Configuration ---
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Unique identifier for the route to the Content Storage Service (CSS).
            - id: content-storage-service-content-route
            
              # Requests matching the predicate will be forwarded here.
              uri: http://localhost:8083

              # Predicates define the conditions for a request to be routed.
              predicates:
                # This predicate matches if the request path starts with /api/v1/content.
                # The '/**' is a wildcard that matches any subpath.
                - Path=/api/v1/content/**
              filters:
                # This applies our filter that adds the X-User-ID header
                - AddUserIdHeader
            - id: content-storage-service-assets-route
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/assets/**
              # There are no authentication filters on this route
            - id: content-storage-service-presets-route
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/presets/**
              # There are no authentication filters on this route
            - id: notification-service-route
            
              uri: http://localhost:8086

              predicates:
                # This predicate matches if the request path starts with /api/v1/notifications.
                - Path=/api/v1/notifications/**
              filters:
                # This applies our filter that adds the X-User-ID header
                - AddUserIdHeader

            # Route for fetching the user's balance.
            - id: ps-get-balance
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/balance
                - Method=GET
              filters:
                - AddUserIdHeader
              # Other routes on /balance are private and not exposed to users.

            # Route for creating a Stripe checkout session.
            - id: ps-create-checkout
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/payments/create-checkout-session
                - Method=POST
              filters:
                - AddUserIdHeader

            # Route for fetching the unified transaction history.
            - id: ps-get-transactions
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/transactions
                - Method=GET
              filters:
                - AddUserIdHeader

            # Public unauthenticated route for the Stripe webhook
            - id: ps-webhook-public
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/stripe/webhooks
                - Method=POST
              # There are no authentication filters on this route
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:3000"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                allowed-headers:
                  - Authorization
                  - Content-Type
                  - Stripe-Signature
                allow-credentials: true
                #max-age: 3600