# Settings for the 'prod' profile.

# Disable detailed error messages for security
server:
  error:
    include-message: never
    include-binding-errors: never

spring:
  jpa:
    properties:
      hibernate:
        '[format_sql]': false