spring:
  application:
    name: content-storage-service
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    ssl:
      enabled: true

# Port for this service
server:
  port: ${SERVER_PORT}

app:
  rabbitmq:
    exchange: "content_exchange"
    queues:
      generation-results: "q.generation.results"
    routing-keys:
      generation-result: "generation.result"
      # CSS needs to know the prefix for sending requests
      generation-request-prefix: "request.generate."
  services:
    payment-service:
      # URL for the payment service, used by the CSS to manage user balances.
      url: ${PAYMENT_SERVICE_URL}
  openai:
    api-key: ${OPENAI_API_KEY}
    llm:
      url: https://api.openai.com/v1/chat/completions
      model: gpt-4
      temperature: 0.7
      max-tokens: 1024
  pricing:
    ai-text-generation-cost-usd: 1 # 1 cent
    video-generation:
      base: 5 # 5 cents
      per-1000-chars: 7 # 7 cents per 1000 characters

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never