# Settings in this file are ONLY active when the 'dev' profile is used.

# Enable detailed error messages in HTTP responses for easier debugging
server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      authentication-database: admin