spring:
  application:
    name: content-storage-service
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
    ssl:
      enabled: true

# Port for this service
server:
  port: ${SERVER_PORT}

app:
  rabbitmq:
    exchange: "content_exchange"
    queues:
      generation-results: "q.generation.results"
    routing-keys:
      generation-result: "generation.result"
      # CSS needs to know the prefix for sending requests
      generation-request-prefix: "request.generate."
  services:
    payment-service:
      # URL for the payment service, used by the CSS to manage user balances.
      url: ${PAYMENT_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never