# Settings for the 'prod' profile.

# Disable detailed error messages for security
server:
  error:
    include-message: never
    include-binding-errors: never

spring:
  data:
    mongodb:
      # PASSWORD IS ASSUMED TO BE URI ENCODED
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      ssl:
        enabled: true
        bundle: awscert
  ssl:
    bundle:
      pem:
        awscert:
          truststore:
            certificate: classpath:global-bundle.pem