# Settings in this file are ONLY active when the 'dev' profile is used.

# Enable detailed error messages in HTTP responses for easier debugging
server:
  error:
    include-message: always
    include-binding-errors: always

# Connection details for local services running in Docker
spring:
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/content_db?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/shorts-creator-realm